// FLTK port of openmpt/mptrack/DefaultKeyBindings.h

#include "openmpt/all/BuildSettings.hpp"
#include "ui/Ui.h"

#pragma once

#include "CommandSet.h"


OPENMPT_NAMESPACE_BEGIN

namespace
{

struct DefaultKeybinding
{
	CommandID cmd;
	uint16 key;  // Virtual key code, or scan code if high bit is set
	FlagSet<Modifiers> modifiers;
	FlagSet<KeyEventType> events;
	Version addedInVersion;
};

constexpr DefaultKeybinding DefaultKeybindings[] =
// clang-format off
{
	{kcFileNew,                                'N',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcFileOpen,                               'O',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcFileClose,                              'W',                ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcFileCloseAll,                           'W',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcFileSave,                               'S',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcFileSaveAs,                             'S',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcPrevDocument,                           ui::Key_BROWSER_BACK,    ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcNextDocument,                           ui::Key_BROWSER_FORWARD, ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPlayPauseSong,                          ui::Key_F5,              ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPauseSong,                              ui::Key_F8,              ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcStopSong,                               ui::Key_ESCAPE,          ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPlaySongFromStart,                      ui::Key_F6,              ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPlaySongFromCursor,                     ui::Key_F6,              ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPlayPatternFromStart,                   ui::Key_F7,              ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPlayPatternFromCursor,                  ui::Key_F7,              ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcMidiRecord,                             ui::Key_F9,              ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcEditUndo,                               'Z',                ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcEditRedo,                               'Y',                ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcEditRedo,                               'Z',                ModShift | ModCtrl, kKeyEventDown | kKeyEventRepeat, MPT_V("1.32.00.25")},
	{kcEditCut,                                'X',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcEditCopy,                               'C',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcEditPaste,                              'V',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcEditPaste,                              ui::Key_INSERT,          ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcEditMixPaste,                           'V',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcEditPasteFlood,                         'V',                ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcEditPushForwardPaste,                   'V',                ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcEditSelectAll,                          '5',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcEditFind,                               'F',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcEditFindNext,                           ui::Key_F3,              ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcViewGeneral,                            'G',                ModAlt,             kKeyEventDown,                   MPT_V("1.31")},
	{kcViewPattern,                            'P',                ModAlt,             kKeyEventDown,                   MPT_V("1.31")},
	{kcViewSamples,                            'S',                ModAlt,             kKeyEventDown,                   MPT_V("1.31")},
	{kcViewInstruments,                        'N',                ModAlt,             kKeyEventDown,                   MPT_V("1.31")},
	{kcViewComments,                           ui::Key_F9,              ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcViewComments,                           'C',                ModAlt,             kKeyEventDown,                   MPT_V("1.31")},
	{kcViewTree,                               ui::Key_F2,              ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcViewOptions,                            ui::Key_F1,              ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcViewMIDImapping,                        ui::Key_F3,              ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSwitchToInstrLibrary,                   'I',                ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcViewToggle,                             ui::Key_TAB,             ModCtrl | ModShift, kKeyEventDown,                   MPT_V("1.32.01.06")},
	{kcHelp,                                   ui::Key_F1,              ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcContextMenu,                            ui::Key_APPS,            ModNone,            kKeyEventDown,                   MPT_V("1.32.00.25")},
	{kcContextMenu,                            ui::Key_F10,             ModShift,           kKeyEventDown,                   MPT_V("1.32.00.25")},
	{kcPrevInstrument,                         ui::Key_DIVIDE,          ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPrevInstrument,                         ui::Key_UP,              ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNextInstrument,                         ui::Key_MULTIPLY,        ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNextInstrument,                         ui::Key_DOWN,            ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPrevOctave,                             ui::Key_DIVIDE,          ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNextOctave,                             ui::Key_MULTIPLY,        ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPrevOrder,                              ui::Key_LEFT,            ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNextOrder,                              ui::Key_RIGHT,           ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPatternJumpDownh1,                      ui::Key_NEXT,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPatternJumpUph1,                        ui::Key_PRIOR,           ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPatternJumpDownh2,                      ui::Key_NEXT,            ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPatternJumpUph2,                        ui::Key_PRIOR,           ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPatternSnapDownh2,                      ui::Key_NEXT,            ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPatternSnapUph2,                        ui::Key_PRIOR,           ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPrevEntryInColumn,                      ui::Key_UP,              ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNextEntryInColumn,                      ui::Key_DOWN,            ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNavigateDown,                           ui::Key_DOWN,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNavigateUp,                             ui::Key_UP,              ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNavigateDownBySpacing,                  ui::Key_DOWN,            ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNavigateUpBySpacing,                    ui::Key_UP,              ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNavigateLeft,                           ui::Key_LEFT,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNavigateRight,                          ui::Key_RIGHT,           ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNavigateNextChan,                       ui::Key_TAB,             ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNavigatePrevChan,                       ui::Key_TAB,             ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcHomeHorizontal,                         ui::Key_HOME,            ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcHomeVertical,                           ui::Key_HOME,            ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcHomeAbsolute,                           ui::Key_HOME,            ModCtrl | ModAlt,   kKeyEventDown,                   MPT_V("1.31")},
	{kcEndHorizontal,                          ui::Key_END,             ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcEndVertical,                            ui::Key_END,             ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcEndAbsolute,                            ui::Key_END,             ModCtrl | ModAlt,   kKeyEventDown,                   MPT_V("1.31")},
	{kcSelect,                                 ui::Key_SHIFT,           ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcCopySelect,                             ui::Key_CONTROL,         ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSelectChannel,                          'L',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSelectColumn,                           'L',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcSelectBeat,                             'B',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSelectMeasure,                          'B',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcToggleFollowSong,                       ui::Key_CANCEL,          ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcToggleFollowSong,                       ui::Key_SCROLL,          ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcToggleFollowSong,                       ui::Key_F11,             ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcCursorCopy,                             ui::Key_RETURN,          ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcCursorPaste,                            ui::Key_SPACE,           ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPatternRecord,                          ui::Key_SPACE,           ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcToggleMetronome,                        'M',                ModAlt,             kKeyEventDown,                   MPT_V("1.32.00.39")},
	{kcPatternPlayRow,                         ui::Key_RETURN,          ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcSetSpacing,                             ui::Key_MENU,            ModAlt,             kKeyEventDown,                   MPT_V("1.31")},
	{kcSwitchToOrderList,                      ui::Key_TAB,             ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcDuplicatePattern,                       'D',                ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPatternEditPCNotePlugin,                ui::Key_OEM_2,           ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcTogglePluginEditor,                     'P',                ModCtrl | ModAlt,   kKeyEventDown,                   MPT_V("1.31")},
	{kcShowNoteProperties,                     ui::Key_APPS,            ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcShowPatternProperties,                  'P',                ModShift | ModAlt,  kKeyEventDown,                   MPT_V("1.31")},
	{kcShowSplitKeyboardSettings,              'E',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcChangeLoopStatus,                       ui::Key_F11,             ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcTimeAtRow,                              'P',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcQuantizeSettings,                       'Q',                ModAlt,             kKeyEventDown,                   MPT_V("1.31")},
	{kcToggleClipboardManager,                 'M',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcClipboardPrev,                          ui::Key_LEFT,            ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcClipboardNext,                          ui::Key_RIGHT,           ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcChannelMute,                            ui::Key_F10,             ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcChannelSolo,                            ui::Key_F10,             ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcChannelUnmuteAll,                       ui::Key_F10,             ModCtrl | ModAlt,   kKeyEventDown,                   MPT_V("1.31")},
	{kcChannelRecordSelect,                    '1',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcChannelSplitRecordSelect,               '2',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcChannelReset,                           'R',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcTransposeUp,                            'Q',                ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcTransposeDown,                          'A',                ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcTransposeOctUp,                         'Q',                ModShift | ModCtrl, kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcTransposeOctDown,                       'A',                ModShift | ModCtrl, kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcTransposeCustom,                        'T',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcDataEntryUp,                            ui::Key_ADD,             ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcDataEntryUp,                            ui::Key_OEM_PLUS,        ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcDataEntryDown,                          ui::Key_SUBTRACT,        ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcDataEntryDown,                          ui::Key_OEM_MINUS,       ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcDataEntryUpCoarse,                      ui::Key_ADD,             ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcDataEntryUpCoarse,                      ui::Key_OEM_PLUS,        ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcDataEntryDownCoarse,                    ui::Key_SUBTRACT,        ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcDataEntryDownCoarse,                    ui::Key_OEM_MINUS,       ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcPatternAmplify,                         'M',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPatternInterpolateVol,                  'J',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPatternInterpolateEffect,               'K',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPatternVisualizeEffect,                 'B',                ModAlt,             kKeyEventDown,                   MPT_V("1.31")},
	{kcPatternGoto,                            'G',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPatternSetInstrument,                   'I',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcPatternGrowSelection,                   'E',                ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPatternShrinkSelection,                 'D',                ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPatternExpand,                          'E',                ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.32.01.06")},
	{kcPatternShrink,                          'D',                ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.32.01.06")},
	{kcClearField,                             ui::Key_DELETE,          ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcClearFieldITStyle,                      ui::Key_OEM_PERIOD,      ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcClearRowStep,                           ui::Key_DELETE,          ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcClearFieldStepITStyle,                  ui::Key_DELETE,          ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcDeleteRow,                              ui::Key_BACK,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcDeleteWholeRow,                         ui::Key_BACK,            ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcDeleteRowGlobal,                        ui::Key_BACK,            ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcDeleteWholeRowGlobal,                   ui::Key_BACK,            ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInsertRow,                              ui::Key_INSERT,          ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInsertWholeRow,                         ui::Key_INSERT,          ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInsertRowGlobal,                        ui::Key_INSERT,          ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInsertWholeRowGlobal,                   ui::Key_INSERT,          ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPrevPattern,                            ui::Key_SUBTRACT,        ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNextPattern,                            ui::Key_ADD,             ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPrevSequence,                           ui::Key_OEM_MINUS,       ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcPrevSequence,                           ui::Key_SUBTRACT,        ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNextSequence,                           ui::Key_OEM_PLUS,        ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcNextSequence,                           ui::Key_ADD,             ModCtrl | ModAlt,   kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcVPNoteC_0,                              16 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteCS0,                              17 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteD_0,                              18 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteDS0,                              19 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteE_0,                              20 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteF_0,                              21 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteFS0,                              22 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteG_0,                              23 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteGS0,                              24 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteA_1,                              25 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteAS1,                              26 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteB_1,                              27 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteC_1,                              30 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteCS1,                              31 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteD_1,                              32 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteDS1,                              33 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteE_1,                              34 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteF_1,                              35 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteFS1,                              36 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteG_1,                              37 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteGS1,                              38 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteA_2,                              39 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteAS2,                              40 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteB_2,                              43 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteC_2,                              44 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteCS2,                              45 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteD_2,                              46 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteDS2,                              47 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteE_2,                              48 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteF_2,                              49 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteFS2,                              50 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteG_2,                              51 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteGS2,                              52 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVPNoteA_3,                              53 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave0,                             '0',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave0,                             ui::Key_NUMPAD0,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave1,                             '1',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave1,                             ui::Key_NUMPAD1,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave2,                             '2',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave2,                             ui::Key_NUMPAD2,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave3,                             '3',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave3,                             ui::Key_NUMPAD3,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave4,                             '4',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave4,                             ui::Key_NUMPAD4,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave5,                             '5',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave5,                             ui::Key_NUMPAD5,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave6,                             '6',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave6,                             ui::Key_NUMPAD6,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave7,                             '7',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave7,                             ui::Key_NUMPAD7,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave8,                             '8',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave8,                             ui::Key_NUMPAD8,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave9,                             '9',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetOctave9,                             ui::Key_NUMPAD9,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcChordModifier,                          ui::Key_SHIFT,           ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcNoteCut,                                ui::Key_OEM_3,           ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcNoteCut,                                41 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31.12.02")},
	{kcNoteOff,                                ui::Key_OEM_PLUS,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcNoteOff,                                13 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31.12.02")},
	{kcNoteFade,                               ui::Key_OEM_PLUS,        ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcNoteFade,                               13 | 0x8000,        ModShift,           kKeyEventDown,                   MPT_V("1.31.12.02")},
	{kcNotePC,                                 ui::Key_OEM_MINUS,       ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcNotePC,                                 12 | 0x8000,        ModShift,           kKeyEventDown,                   MPT_V("1.31.12.02")},
	{kcNotePCS,                                ui::Key_OEM_MINUS,       ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcNotePCS,                                12 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.31.12.02")},
	{kcSetIns0,                                ui::Key_NUMPAD0,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns0,                                '0',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns1,                                ui::Key_NUMPAD1,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns1,                                '1',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns2,                                ui::Key_NUMPAD2,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns2,                                '2',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns3,                                ui::Key_NUMPAD3,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns3,                                '3',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns4,                                ui::Key_NUMPAD4,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns4,                                '4',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns5,                                ui::Key_NUMPAD5,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns5,                                '5',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns6,                                ui::Key_NUMPAD6,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns6,                                '6',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns7,                                ui::Key_NUMPAD7,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns7,                                '7',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns8,                                ui::Key_NUMPAD8,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns8,                                '8',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns9,                                ui::Key_NUMPAD9,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetIns9,                                '9',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume0,                             '0',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume0,                             ui::Key_NUMPAD0,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume1,                             '1',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume1,                             ui::Key_NUMPAD1,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume2,                             '2',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume2,                             ui::Key_NUMPAD2,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume3,                             '3',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume3,                             ui::Key_NUMPAD3,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume4,                             '4',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume4,                             ui::Key_NUMPAD4,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume5,                             '5',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume5,                             ui::Key_NUMPAD5,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume6,                             '6',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume6,                             ui::Key_NUMPAD6,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume7,                             '7',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume7,                             ui::Key_NUMPAD7,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume8,                             '8',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume8,                             ui::Key_NUMPAD8,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume9,                             '9',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolume9,                             ui::Key_NUMPAD9,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeVol,                           'V',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumePan,                           'P',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeVolSlideUp,                    'C',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeVolSlideDown,                  'D',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeFineVolUp,                     'A',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeFineVolDown,                   'B',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeVibratoSpd,                    'U',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeVibrato,                       'H',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeXMPanLeft,                     'L',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeXMPanRight,                    'R',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumePortamento,                    'G',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeITPortaUp,                     'F',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeITPortaDown,                   'E',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetVolumeITOffset,                      'O',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXmacroSlide,                        ui::Key_OEM_5,           ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXdelaycut,                          ui::Key_OEM_1,           ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXdelaycut,                          ui::Key_OEM_1,           ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXextension,                         ui::Key_OEM_2,           ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXFinetune,                          ui::Key_OEM_PLUS,        ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXFinetuneSmooth,                    ui::Key_OEM_PLUS,        ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam0,                            '0',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam0,                            ui::Key_NUMPAD0,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam1,                            '1',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam1,                            ui::Key_NUMPAD1,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam2,                            '2',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam2,                            ui::Key_NUMPAD2,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam3,                            '3',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam3,                            ui::Key_NUMPAD3,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam4,                            '4',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam4,                            ui::Key_NUMPAD4,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam5,                            '5',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam5,                            ui::Key_NUMPAD5,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam6,                            '6',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam6,                            ui::Key_NUMPAD6,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam7,                            '7',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam7,                            ui::Key_NUMPAD7,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam8,                            '8',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam8,                            ui::Key_NUMPAD8,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam9,                            '9',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParam9,                            ui::Key_NUMPAD9,         ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParamA,                            'A',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParamB,                            'B',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParamC,                            'C',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParamD,                            'D',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParamE,                            'E',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSetFXParamF,                            'F',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleLoad,                             ui::Key_RETURN,          ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleLoadRaw,                          ui::Key_RETURN,          ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleTransposeUp,                      'Q',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleTransposeDown,                    'A',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleTransposeOctUp,                   'Q',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleTransposeOctDown,                 'A',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleFinetuneUp,                       ui::Key_UP,              ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31.00.26")},
	{kcSampleFinetuneDown,                     ui::Key_DOWN,            ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31.00.26")},
	{kcSampleToggleFollowPlayCursor,           'F',                ModShift,           kKeyEventDown,                   MPT_V("1.31.00.19")},
	{kcSampleTrim,                             'T',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleTrimToLoopEnd,                    'T',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleSilence,                          ui::Key_BACK,            ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleNormalize,                        'N',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleAmplify,                          'M',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleReverse,                          'R',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleDelete,                           ui::Key_DELETE,          ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleZoomUp,                           ui::Key_ADD,             ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcSampleZoomUp,                           ui::Key_OEM_PLUS,        ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcSampleZoomDown,                         ui::Key_SUBTRACT,        ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcSampleZoomDown,                         ui::Key_OEM_MINUS,       ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcSampleZoomSelection,                    ui::Key_SPACE,           ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleCenterSampleStart,                '1',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleCenterSampleEnd,                  '2',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleCenterLoopStart,                  '1',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleCenterLoopEnd,                    '2',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleCenterSustainStart,               '3',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleCenterSustainEnd,                 '4',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSample8Bit,                             '8',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleMonoMix,                          'M',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleMonoLeft,                         'L',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleMonoRight,                        'R',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleMonoSplit,                        'S',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleStereoSep,                        'P',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleUpsample,                         'F',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleDownsample,                       'G',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleResample,                         'R',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleInvert,                           'I',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleSignUnsign,                       'U',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleRemoveDCOffset,                   'E',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleQuickFade,                        'D',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcSampleXFade,                            'L',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{CommandID(kcStartSampleCues + 0),         '1',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{CommandID(kcStartSampleCues + 1),         '2',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{CommandID(kcStartSampleCues + 2),         '3',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{CommandID(kcStartSampleCues + 3),         '4',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{CommandID(kcStartSampleCues + 4),         '5',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{CommandID(kcStartSampleCues + 5),         '6',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{CommandID(kcStartSampleCues + 6),         '7',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{CommandID(kcStartSampleCues + 7),         '8',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{CommandID(kcStartSampleCues + 8),         '9',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeZoomIn,               ui::Key_ADD,             ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopeZoomIn,               ui::Key_OEM_PLUS,        ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopeZoomOut,              ui::Key_SUBTRACT,        ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopeZoomOut,              ui::Key_OEM_MINUS,       ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopeScale,                'E',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSwitchToVolume,       'M',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSwitchToPanning,      'P',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSwitchToPitch,        'I',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeToggleVolume,         'M',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeTogglePanning,        'P',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeTogglePitch,          'I',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeToggleFilter,         'F',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeToggleLoop,           'L',                ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSelectLoopStart,      ui::Key_HOME,            ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSelectLoopEnd,        ui::Key_END,             ModShift,           kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeToggleSustain,        'L',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSelectSustainStart,   ui::Key_HOME,            ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSelectSustainEnd,     ui::Key_END,             ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeToggleCarry,          'C',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopePointPrev,            ui::Key_TAB,             ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopePointNext,            ui::Key_TAB,             ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopePointMoveLeft,        ui::Key_LEFT,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopePointMoveRight,       ui::Key_RIGHT,           ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopePointMoveLeftCoarse,  ui::Key_LEFT,            ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopePointMoveRightCoarse, ui::Key_RIGHT,           ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopePointMoveUp,          ui::Key_UP,              ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopePointMoveUp8,         ui::Key_PRIOR,           ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopePointMoveDown,        ui::Key_DOWN,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopePointMoveDown8,       ui::Key_NEXT,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcInstrumentEnvelopePointInsert,          ui::Key_INSERT,          ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopePointRemove,          ui::Key_DELETE,          ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopePointRemove,          ui::Key_BACK,            ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSetLoopStart,         ui::Key_HOME,            ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSetLoopEnd,           ui::Key_END,             ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSetSustainLoopStart,  ui::Key_HOME,            ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeSetSustainLoopEnd,    ui::Key_END,             ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentEnvelopeToggleReleaseNode,    'R',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcToggleSmpInsList,                       ui::Key_TAB,             ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcExecuteSmpInsListItem,                  ui::Key_RETURN,          ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcRenameSmpInsListItem,                   ui::Key_RETURN,          ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcTreeViewSwitchViews,                    ui::Key_TAB,             ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31.00.27")},
	{kcTreeViewOpen,                           ui::Key_RETURN,          ModNone,            kKeyEventDown,                   MPT_V("1.31.00.14")},
	{kcTreeViewPlay,                           ui::Key_SPACE,           ModNone,            kKeyEventDown,                   MPT_V("1.31.00.14")},
	{kcTreeViewInsert,                         ui::Key_INSERT,          ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31.00.14")},
	{kcTreeViewDuplicate,                      ui::Key_INSERT,          ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31.00.14")},
	{kcTreeViewDelete,                         ui::Key_DELETE,          ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31.00.14")},
	{kcTreeViewDeletePermanently,              ui::Key_DELETE,          ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31.00.16")},
	{kcTreeViewMoveUp,                         ui::Key_UP,              ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.33.00.12")},
	{kcTreeViewMoveDown,                       ui::Key_DOWN,            ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.33.00.12")},
	{kcTreeViewRename,                         ui::Key_RETURN,          ModCtrl,            kKeyEventDown,                   MPT_V("1.31.00.14")},
	{kcTreeViewSendToEditorInsertNew,          ui::Key_RETURN,          ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31.00.15")},
	{kcTreeViewFolderUp,                       ui::Key_BACK,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31.00.27")},
	{kcTreeViewFind,                           'F',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31.00.14")},
	{kcVSTGUIPrevPreset,                       ui::Key_SUBTRACT,        ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcVSTGUINextPreset,                       ui::Key_ADD,             ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcVSTGUIPrevPresetJump,                   ui::Key_SUBTRACT,        ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcVSTGUINextPresetJump,                   ui::Key_ADD,             ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcVSTGUIRandParams,                       'D',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcVSTGUIToggleRecordParams,               'R',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVSTGUIToggleSendKeysToPlug,             'K',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcVSTGUIBypassPlug,                       'B',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInstrumentCtrlDuplicate,                'D',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInsNoteMapEditSampleMap,                'E',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInsNoteMapEditSample,                   'E',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInsNoteMapCopyCurrentNote,              'M',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInsNoteMapCopyCurrentSample,            'M',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInsNoteMapReset,                        'R',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInsNoteMapTransposeUp,                  'Q',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInsNoteMapTransposeDown,                'A',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcInsNoteMapTransposeOctUp,               'Q',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcInsNoteMapTransposeOctDown,             'A',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcOrderlistEditDelete,                    ui::Key_DELETE,          ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistEditInsert,                    ui::Key_INSERT,          ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistEditInsertSeparator,           ui::Key_INSERT,          ModCtrl,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistEditCopyOrders,                'C',                ModShift | ModCtrl, kKeyEventDown,                   MPT_V("1.31")},
	{kcOrderlistEditPattern,                   ui::Key_RETURN,          ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistSwitchToPatternView,           ui::Key_TAB,             ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistNavigateLeft,                  ui::Key_LEFT,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistNavigateLeft,                  ui::Key_UP,              ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistNavigateRight,                 ui::Key_RIGHT,           ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistNavigateRight,                 ui::Key_DOWN,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistNavigateFirst,                 ui::Key_HOME,            ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistNavigateLast,                  ui::Key_END,             ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat0,                          '0',                ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat0,                          ui::Key_NUMPAD0,         ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat1,                          '1',                ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat1,                          ui::Key_NUMPAD1,         ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat2,                          '2',                ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat2,                          ui::Key_NUMPAD2,         ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat3,                          '3',                ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat3,                          ui::Key_NUMPAD3,         ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat4,                          '4',                ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat4,                          ui::Key_NUMPAD4,         ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat5,                          '5',                ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat5,                          ui::Key_NUMPAD5,         ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat6,                          '6',                ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat6,                          ui::Key_NUMPAD6,         ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat7,                          '7',                ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat7,                          ui::Key_NUMPAD7,         ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat8,                          '8',                ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat8,                          ui::Key_NUMPAD8,         ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat9,                          '9',                ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPat9,                          ui::Key_NUMPAD9,         ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPatPlus,                       ui::Key_ADD,             ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPatPlus,                       ui::Key_OEM_PLUS,        ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPatMinus,                      ui::Key_SUBTRACT,        ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPatMinus,                      ui::Key_OEM_MINUS,       ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcOrderlistPatIgnore,                     'I',                ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcOrderlistPatInvalid,                    ui::Key_SPACE,           ModNone,            kKeyEventDown,                   MPT_V("1.31")},
	{kcOrderlistLockPlayback,                  'L',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcOrderlistUnlockPlayback,                'U',                ModCtrl,            kKeyEventDown,                   MPT_V("1.31")},
	{kcOrderlistQueueAtPatternEnd,             'Q',                ModNone,            kKeyEventDown,                   MPT_V("1.32.00.05")},
	{kcOrderlistQueueAtMeasureEnd,             'Q',                ModShift,           kKeyEventDown,                   MPT_V("1.32.00.05")},
	{kcOrderlistQueueAtBeatEnd,                'Q',                ModAlt,             kKeyEventDown,                   MPT_V("1.32.00.05")},
	{kcOrderlistQueueAtRowEnd,                 'Q',                ModShift | ModAlt,  kKeyEventDown,                   MPT_V("1.32.00.05")},
	{kcChnSettingsPrev,                        ui::Key_LEFT,            ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcChnSettingsPrev,                        ui::Key_BACK,            ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcChnSettingsNext,                        ui::Key_RIGHT,           ModAlt,             kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcChnSettingsNext,                        ui::Key_RETURN,          ModShift,           kKeyEventDown | kKeyEventRepeat, MPT_V("1.31")},
	{kcChnColorFromPrev,                       ui::Key_LEFT,            ModShift | ModAlt,  kKeyEventDown,                   MPT_V("1.31")},
	{kcChnColorFromNext,                       ui::Key_RIGHT,           ModShift | ModAlt,  kKeyEventDown,                   MPT_V("1.31")},
	{kcChnSettingsClose,                       ui::Key_RETURN,          ModNone,            kKeyEventDown,                   MPT_V("1.31")},
};
// clang-format on

constexpr DefaultKeybinding DefaultKeybindingsIT[] =
// clang-format off
{
	{kcClearFieldStepITStyle,                  52 | 0x8000,        ModNone,            kKeyEventDown | kKeyEventRepeat, MPT_V("1.32")},
	{kcVPNoteC_0,                              44 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteCS0,                              31 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteD_0,                              45 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteDS0,                              32 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteE_0,                              46 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteF_0,                              47 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteFS0,                              34 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteG_0,                              48 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteGS0,                              35 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteA_1,                              49 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteAS1,                              36 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteB_1,                              50 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	
	{kcVPNoteC_1,                              16 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteCS1,                              3  | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteD_1,                              17 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteDS1,                              4  | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteE_1,                              18 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteF_1,                              19 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteFS1,                              6  | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteG_1,                              20 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteGS1,                              7  | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteA_2,                              21 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteAS2,                              8  | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteB_2,                              22 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteC_2,                              23 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteCS2,                              10 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteD_2,                              24 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteDS2,                              11 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteE_2,                              25 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteF_2,                              26 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteFS2,                              13 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteG_2,                              27 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	
	{kcSetOctave0,                             '0',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave0,                             ui::Key_NUMPAD0,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave1,                             '1',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave1,                             ui::Key_NUMPAD1,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave2,                             '2',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave2,                             ui::Key_NUMPAD2,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave3,                             '3',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave3,                             ui::Key_NUMPAD3,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave4,                             '4',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave4,                             ui::Key_NUMPAD4,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave5,                             '5',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave5,                             ui::Key_NUMPAD5,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave6,                             '6',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave6,                             ui::Key_NUMPAD6,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave7,                             '7',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave7,                             ui::Key_NUMPAD7,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave8,                             '8',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave8,                             ui::Key_NUMPAD8,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave9,                             '9',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave9,                             ui::Key_NUMPAD9,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcChordModifier,                          ui::Key_SHIFT,           ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteCut,                                '1',                ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteOff,                                ui::Key_OEM_3,           ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteOff,                                41 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteFade,                               ui::Key_OEM_3,           ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteFade,                               41 | 0x8000,        ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteFade,                               ui::Key_OEM_5,           ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteFade,                               43 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNotePC,                                 ui::Key_OEM_7,           ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNotePC,                                 40 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNotePCS,                                ui::Key_OEM_7,           ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcNotePCS,                                40 | 0x8000,        ModShift,           kKeyEventDown,                   MPT_V("1.32")},
};
// clang-format on

constexpr DefaultKeybinding DefaultKeybindingsFT2[] =
// clang-format off
{
	{kcVPNoteC_1,                              44 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteCS1,                              31 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteD_1,                              45 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteDS1,                              32 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteE_1,                              46 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteF_1,                              47 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteFS1,                              34 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteG_1,                              48 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteGS1,                              35 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteA_2,                              49 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteAS2,                              36 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteB_2,                              50 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteC_2,                              51 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteCS2,                              38 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteD_2,                              52 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteDS2,                              39 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteE_2,                              53 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteFS2,                              43 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},

	{kcVPNoteC_2,                              16 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteCS2,                              3  | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteD_2,                              17 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteDS2,                              4  | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteE_2,                              18 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteF_2,                              19 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteFS2,                              6  | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteG_2,                              20 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteGS2,                              7  | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteA_3,                              21 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteAS3,                              8  | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteB_3,                              22 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteC_3,                              23 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteCS3,                              10 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteD_3,                              24 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteDS3,                              11 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteE_3,                              25 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteF_3,                              26 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteFS3,                              13 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcVPNoteG_3,                              27 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	
	{kcSetOctave0,                             '0',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave0,                             ui::Key_NUMPAD0,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave1,                             '1',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave1,                             ui::Key_NUMPAD1,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave2,                             '2',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave2,                             ui::Key_NUMPAD2,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave3,                             '3',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave3,                             ui::Key_NUMPAD3,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave4,                             '4',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave4,                             ui::Key_NUMPAD4,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave5,                             '5',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave5,                             ui::Key_NUMPAD5,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave6,                             '6',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave6,                             ui::Key_NUMPAD6,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave7,                             '7',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave7,                             ui::Key_NUMPAD7,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave8,                             '8',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave8,                             ui::Key_NUMPAD8,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave9,                             '9',                ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcSetOctave9,                             ui::Key_NUMPAD9,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcChordModifier,                          ui::Key_SHIFT,           ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteCut,                                ui::Key_OEM_3,           ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteCut,                                41 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteOff,                                ui::Key_CAPITAL,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteOff,                                58 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteOff,                                ui::Key_OEM_102,         ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteOff,                                86 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNoteFade,                               '1',                ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNotePC,                                 ui::Key_OEM_7,           ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNotePC,                                 40 | 0x8000,        ModNone,            kKeyEventDown,                   MPT_V("1.32")},
	{kcNotePCS,                                ui::Key_OEM_7,           ModShift,           kKeyEventDown,                   MPT_V("1.32")},
	{kcNotePCS,                                40 | 0x8000,        ModShift,           kKeyEventDown,                   MPT_V("1.32")},
};
// clang-format on

};  // namespace

OPENMPT_NAMESPACE_END
