# Audio and MIDI backends per platform, exported through the mpt_platform interface target
add_library(mpt_platform INTERFACE)

if(WIN32)
	target_link_libraries(mpt_platform INTERFACE winmm)
	set(OPENMPT_RTMIDI_API __WINDOWS_MM__)
	set(OPENMPT_RTMIDI_LIBS winmm)
elseif(APPLE)
	find_library(COREMIDI_LIBRARY CoreMIDI REQUIRED)
	find_library(COREAUDIO_LIBRARY CoreAudio REQUIRED)
	find_library(COREFOUNDATION_LIBRARY CoreFoundation REQUIRED)
	set(OPENMPT_RTMIDI_API __MACOSX_CORE__)
	set(OPENMPT_RTMIDI_LIBS ${COREMIDI_LIBRARY} ${COREAUDIO_LIBRARY} ${COREFOUNDATION_LIBRARY})
else()
	find_package(ALSA REQUIRED)
	find_package(PkgConfig REQUIRED)
	pkg_check_modules(PULSE REQUIRED IMPORTED_TARGET libpulse libpulse-simple)
	target_compile_definitions(mpt_platform INTERFACE MPT_WITH_PULSEAUDIO MPT_WITH_PULSEAUDIOSIMPLE)
	target_link_libraries(mpt_platform INTERFACE PkgConfig::PULSE ALSA::ALSA atomic)
	set(OPENMPT_RTMIDI_API __LINUX_ALSA__)
	set(OPENMPT_RTMIDI_LIBS ALSA::ALSA)
endif()
